services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mcp-server-1:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ID=server-1
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - SERVER_1_URL=http://mcp-server-1:3000
      - SERVER_2_URL=http://mcp-server-2:3000
      - SERVER_3_URL=http://mcp-server-3:3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-server-2:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ID=server-2
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - SERVER_1_URL=http://mcp-server-1:3000
      - SERVER_2_URL=http://mcp-server-2:3000
      - SERVER_3_URL=http://mcp-server-3:3000
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-server-3:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ID=server-3
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - SERVER_1_URL=http://mcp-server-1:3000
      - SERVER_2_URL=http://mcp-server-2:3000
      - SERVER_3_URL=http://mcp-server-3:3000
    ports:
      - "3002:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    depends_on:
      - mcp-server-1
      - mcp-server-2
      - mcp-server-3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data: